package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import static ventanas.Administrador.ventanas_abiertas;

public class AgregarProducto extends javax.swing.JFrame {

    String user = "", direccion_imagen, direccion_origen = "", nombre_imagen;

    public AgregarProducto() {
        initComponents();

        user = Login.user;

        setSize(750, 700);
        setResizable(false);
        setTitle("Agregar producto - Sesion de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper_principal.jpg");
        Icon icono;
        icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);
        this.repaint();

        direccion_imagen = "src/images/productos/indefinido.jpg";
        ImageIcon imagen = new ImageIcon(direccion_imagen);
        Icon icono_imagen = new ImageIcon(imagen.getImage().getScaledInstance(label_imagen.getWidth(),
                label_imagen.getHeight(), Image.SCALE_DEFAULT));
        label_imagen.setIcon(icono_imagen);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        boton_eliminar_imagen = new javax.swing.JButton();
        label_imagen = new javax.swing.JLabel();
        tf_medida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_material = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_ubicacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_precio_venta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_precio_compra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_stock = new javax.swing.JTextField();
        box_unidad_stock = new javax.swing.JComboBox<>();
        tf_codigo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_comentarios_producto = new javax.swing.JTextPane();
        tf_marca = new javax.swing.JTextField();
        boton_agregar_producto = new javax.swing.JButton();
        boton_subir_imagen = new javax.swing.JButton();
        box_unidad_compra = new javax.swing.JComboBox<>();
        box_unidad_venta = new javax.swing.JComboBox<>();
        footer1 = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Ficha de producto");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        tf_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, -1));

        boton_eliminar_imagen.setBackground(new java.awt.Color(0, 153, 153));
        boton_eliminar_imagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_eliminar_imagen.setForeground(new java.awt.Color(255, 255, 255));
        boton_eliminar_imagen.setText("Eliminar");
        boton_eliminar_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminar_imagenActionPerformed(evt);
            }
        });
        getContentPane().add(boton_eliminar_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, 40));

        label_imagen.setText("IMG");
        label_imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 200));

        tf_medida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_medida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_medida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Medida/Tamaño:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        tf_material.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_material.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 200, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Material/es:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        tf_ubicacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_ubicacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 200, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ubicacion:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Comentarios:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Codigo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Precio de venta:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        tf_precio_venta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_precio_venta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_precio_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_precio_ventaKeyTyped(evt);
            }
        });
        getContentPane().add(tf_precio_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 365, 20, 20));

        tf_precio_compra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_precio_compra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_precio_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_precio_compraKeyTyped(evt);
            }
        });
        getContentPane().add(tf_precio_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 435, 20, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Precio de compra:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        tf_stock.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tf_stock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_stock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_stock.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_stockKeyTyped(evt);
            }
        });
        getContentPane().add(tf_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, -1));

        box_unidad_stock.setBackground(new java.awt.Color(0, 153, 153));
        box_unidad_stock.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        box_unidad_stock.setForeground(new java.awt.Color(255, 255, 255));
        box_unidad_stock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U", "Doc", "Cajas", "Kg", "Bolsas", "L" }));
        box_unidad_stock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(box_unidad_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 130, 30));

        tf_codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_codigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_codigo.setEnabled(false);
        getContentPane().add(tf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 200, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Stock:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jScrollPane1.setViewportView(tp_comentarios_producto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 200, 80));

        tf_marca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_marca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, -1));

        boton_agregar_producto.setBackground(new java.awt.Color(0, 153, 153));
        boton_agregar_producto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_agregar_producto.setForeground(new java.awt.Color(255, 255, 255));
        boton_agregar_producto.setText("Agregar");
        boton_agregar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_productoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_agregar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 200, 40));

        boton_subir_imagen.setBackground(new java.awt.Color(0, 153, 153));
        boton_subir_imagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_subir_imagen.setForeground(new java.awt.Color(255, 255, 255));
        boton_subir_imagen.setText("Subir");
        boton_subir_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_subir_imagenActionPerformed(evt);
            }
        });
        getContentPane().add(boton_subir_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 40));

        box_unidad_compra.setBackground(new java.awt.Color(0, 153, 153));
        box_unidad_compra.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        box_unidad_compra.setForeground(new java.awt.Color(255, 255, 255));
        box_unidad_compra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U", "Doc", "Cajas", "Kg", "Bolsas", "L" }));
        box_unidad_compra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(box_unidad_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 130, 30));

        box_unidad_venta.setBackground(new java.awt.Color(0, 153, 153));
        box_unidad_venta.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        box_unidad_venta.setForeground(new java.awt.Color(255, 255, 255));
        box_unidad_venta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U", "Doc", "Cajas", "Kg", "Bolsas", "L" }));
        box_unidad_venta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(box_unidad_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 30));

        footer1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        footer1.setText("Creado por Cosme Fulanito C.O.");
        footer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        footer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footer1MouseClicked(evt);
            }
        });
        getContentPane().add(footer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 620, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_eliminar_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminar_imagenActionPerformed
        // TODO add your handling code here:
        direccion_origen = "";
        
        direccion_imagen = "src/images/productos/indefinido.jpg";
        ImageIcon imagen = new ImageIcon(direccion_imagen);
        Icon icono_imagen = new ImageIcon(imagen.getImage().getScaledInstance(label_imagen.getWidth(),
                label_imagen.getHeight(), Image.SCALE_DEFAULT));
        label_imagen.setIcon(icono_imagen);
        this.repaint();
    }//GEN-LAST:event_boton_eliminar_imagenActionPerformed

    private void tf_stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_stockKeyTyped
        // TODO add your handling code here:
        filtroMonto(evt, tf_stock);
    }//GEN-LAST:event_tf_stockKeyTyped

    private void tf_precio_ventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_precio_ventaKeyTyped
        // TODO add your handling code here:
        filtroMonto(evt, tf_precio_venta);
    }//GEN-LAST:event_tf_precio_ventaKeyTyped

    private void tf_precio_compraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_precio_compraKeyTyped
        // TODO add your handling code here:
        filtroMonto(evt, tf_precio_compra);
    }//GEN-LAST:event_tf_precio_compraKeyTyped

    private void boton_agregar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_productoActionPerformed
        // TODO add your handling code here:
        String nombre, medida, material, marca, ubicacion, comentarios, stock_string, unidadS, preciov_string, precioc_string, unidadV, unidadC, fecha;
        int validacion = 0;
        float preciov, precioc, stock;

        DateTimeFormatter ult = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        fecha = ult.format(LocalDateTime.now());

        nombre = tf_nombre.getText();
        medida = tf_medida.getText();
        material = tf_material.getText();
        marca = tf_marca.getText();
        ubicacion = tf_ubicacion.getText();
        comentarios = tp_comentarios_producto.getText();
        stock_string = tf_stock.getText().trim();
        unidadS = box_unidad_stock.getSelectedItem().toString();
        preciov_string = tf_precio_venta.getText().trim();
        unidadV = box_unidad_venta.getSelectedItem().toString();
        precioc_string = tf_precio_compra.getText().trim();
        unidadC = box_unidad_compra.getSelectedItem().toString();

        if (stock_string.equals("")) {
            stock = 0;
        } else {
            stock = Float.parseFloat(stock_string);
        }
        if (preciov_string.equals("")) {
            preciov = 0;
        } else {
            preciov = Float.parseFloat(preciov_string);
        }
        if (precioc_string.equals("")) {
            precioc = 0;
        } else {
            precioc = Float.parseFloat(precioc_string);
        }
        
        if (!direccion_origen.equals("")) {
            direccion_imagen = direccion_origen;
            Path origenPath = FileSystems.getDefault().getPath(direccion_origen);

            Random rand = new Random();
            direccion_imagen = "src/images/productos/" + rand.nextInt(100) + nombre_imagen;
            Path destinoPath = FileSystems.getDefault().getPath(direccion_imagen);
            try {
                Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException e) {
                System.err.println("Error al subir la imagen" + e);
            }
        }

        if (nombre.equals("")) {
            tf_nombre.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into productos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setInt(1, 0);
                pst.setString(2, nombre);
                pst.setString(3, medida);
                pst.setString(4, material);
                pst.setString(5, marca);
                pst.setString(6, ubicacion);
                pst.setString(7, comentarios);
                pst.setString(8, fecha);
                pst.setFloat(9, stock);
                pst.setString(10, unidadS);
                pst.setDouble(11, preciov);
                pst.setString(12, unidadV);
                pst.setDouble(13, precioc);
                pst.setString(14, unidadC);
                pst.setString(15, fecha);
                pst.setString(16, fecha);
                pst.setString(17, direccion_imagen);

                pst.executeUpdate();
                cn.close();

                boton_agregar_producto.setBackground(Color.green);

                JOptionPane.showMessageDialog(null, "Producto agregado");
                this.dispose();
            } catch (SQLException e) {
                System.err.println("Error al agregar producto" + e);
                JOptionPane.showMessageDialog(null, "Error al agregar producto, contacte al administrador");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos");
        }
    }//GEN-LAST:event_boton_agregar_productoActionPerformed

    private void boton_subir_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_subir_imagenActionPerformed
        // TODO add your handling code here:
        //creo file choser
        JFileChooser fc = new JFileChooser();

        //creo e indico filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.JPG", "jpg", "*.PNG", "png");
        fc.setFileFilter(filtro);

        //abre buscador
        int seleccion = fc.showOpenDialog(this);

        //cuando se presiona aceptar:
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fc.getSelectedFile();
            direccion_origen = fichero.getAbsolutePath();
            nombre_imagen = fichero.getName();

            ImageIcon imagen = new ImageIcon(direccion_origen);
            Icon icono_imagen = new ImageIcon(imagen.getImage().getScaledInstance(label_imagen.getWidth(),
                    label_imagen.getHeight(), Image.SCALE_DEFAULT));
            label_imagen.setIcon(icono_imagen);
            this.repaint();
        }
    }//GEN-LAST:event_boton_subir_imagenActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ventanas_abiertas.remove(ventanas_abiertas.indexOf("agregar"));
    }//GEN-LAST:event_formWindowClosed

    private void footer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footer1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Por soporte tecnico comuniquese al e-mail: soporte@lachucha.com.ar");
    }//GEN-LAST:event_footer1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_agregar_producto;
    private javax.swing.JButton boton_eliminar_imagen;
    private javax.swing.JButton boton_subir_imagen;
    private javax.swing.JComboBox<String> box_unidad_compra;
    private javax.swing.JComboBox<String> box_unidad_stock;
    private javax.swing.JComboBox<String> box_unidad_venta;
    private javax.swing.JLabel footer1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_medida;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_precio_compra;
    private javax.swing.JTextField tf_precio_venta;
    private javax.swing.JTextField tf_stock;
    private javax.swing.JTextField tf_ubicacion;
    private javax.swing.JTextPane tp_comentarios_producto;
    // End of variables declaration//GEN-END:variables

    public void filtroMonto(KeyEvent evt, JTextField lab) {
        int key = evt.getKeyChar();

        boolean numeros;

        numeros = (key >= 48 && key <= 57) || key == 46;

        if (lab.getText().contains(".")) {
            numeros = (key >= 48 && key <= 57);
        }

        if (!numeros) {
            evt.consume();
        }
    }
}
