package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static ventanas.Administrador.ventanas_abiertas;

public class Nivel1 extends javax.swing.JFrame {

    String user, user_nivel;

    public Nivel1() {
        initComponents();

        user = Login.user;
        user_nivel = Login.user_nivel;

        setSize(530, 300);
        setResizable(false);
        setTitle("Ventas - Sesion de " + user);
        setLocationRelativeTo(null);

        if (user_nivel.equals("Administrador")) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper_principal.jpg");
        Icon icono;
        icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        boton_listaRemitos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        boton_stock = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_nuevaFactura = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Ventas");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 40));

        boton_listaRemitos.setBackground(new java.awt.Color(0, 153, 153));
        boton_listaRemitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remitos.png"))); // NOI18N
        boton_listaRemitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_listaRemitosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_listaRemitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 120, 100));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Remitos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        boton_stock.setBackground(new java.awt.Color(0, 153, 153));
        boton_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock.png"))); // NOI18N
        boton_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_stockActionPerformed(evt);
            }
        });
        getContentPane().add(boton_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Stock");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 170, -1, -1));

        boton_nuevaFactura.setBackground(new java.awt.Color(0, 153, 153));
        boton_nuevaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png"))); // NOI18N
        boton_nuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nuevaFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_nuevaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 100));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Nueva factura");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 170, -1, -1));

        footer.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        footer.setText("Creado por Cosme Fulanito C.O.");
        footer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        footer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerMouseClicked(evt);
            }
        });
        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 220, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_listaRemitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_listaRemitosActionPerformed
        // TODO add your handling code here:
        ListaRemitos listaR = new ListaRemitos();

        if (!ventanas_abiertas.contains("listaR")) {
            ventanas_abiertas.add("listaR");
            listaR.setVisible(true);
        }

    }//GEN-LAST:event_boton_listaRemitosActionPerformed

    private void boton_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_stockActionPerformed
        // TODO add your handling code here:
        Stock stock = new Stock();

        if (!ventanas_abiertas.contains("stock")) {
            ventanas_abiertas.add("stock");
            stock.setVisible(true);
        }
        
    }//GEN-LAST:event_boton_stockActionPerformed

    private void boton_nuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevaFacturaActionPerformed
        // TODO add your handling code here:
        Factura factura = new Factura();
        
        if (!ventanas_abiertas.contains("factura")) {
            ventanas_abiertas.add("factura");
            factura.setVisible(true);
        }
        
    }//GEN-LAST:event_boton_nuevaFacturaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ventanas_abiertas.remove(ventanas_abiertas.indexOf("nivel1"));
    }//GEN-LAST:event_formWindowClosed

    private void footerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Por soporte tecnico comuniquese al e-mail: soporte@lachucha.com.ar");
    }//GEN-LAST:event_footerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_listaRemitos;
    private javax.swing.JButton boton_nuevaFactura;
    private javax.swing.JButton boton_stock;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables
}
