package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static ventanas.Administrador.ventanas_abiertas;

public class RegistrarUsuario extends javax.swing.JFrame {

    String user;

    public RegistrarUsuario() {
        initComponents();

        user = Login.user;

        setSize(700, 350);
        setResizable(false);
        setTitle("Registrar usuario - Sesion de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper_principal.jpg");
        Icon icono;
        icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        box_nivel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JTextField();
        boton_registrar = new javax.swing.JButton();
        footer = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Registrar usuario");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 40));

        tf_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        tf_telefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nivel:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        box_nivel.setBackground(new java.awt.Color(0, 153, 153));
        box_nivel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        box_nivel.setForeground(new java.awt.Color(255, 255, 255));
        box_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Administrador", "1", "2" }));
        box_nivel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(box_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 25));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        tf_username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 200, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        tf_pass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 200, -1));

        boton_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 120, 100));

        footer.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        footer.setText("Creado por Cosme Fulanito C.O.");
        footer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        footer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerMouseClicked(evt);
            }
        });
        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed
        // TODO add your handling code here:
        int validacion = 0;
        String nombre, telefono, username, pass, nivel;

        username = tf_username.getText().trim();
        pass = tf_pass.getText().trim();
        nombre = tf_nombre.getText().trim();
        telefono = tf_telefono.getText().trim();
        nivel = (String) box_nivel.getSelectedItem();

        if (nombre.equals("")) {
            tf_nombre.setBackground(Color.red);
            validacion++;
        } else {
            tf_nombre.setBackground(Color.white);
        }
        
        if (username.equals("")) {
            tf_username.setBackground(Color.red);
            validacion++;
        } else {
            tf_username.setBackground(Color.white);
        }
        
        if (pass.equals("")) {
            tf_pass.setBackground(Color.red);
            validacion++;
        } else {
            tf_pass.setBackground(Color.white);
        }
        
        if (telefono.equals("")) {
            tf_telefono.setBackground(Color.red);
            validacion++;
        } else {
            tf_telefono.setBackground(Color.white);
        }
        
        if (nivel.equals(" ")) {
            box_nivel.setBackground(Color.red);
            validacion++;
        } else {
            box_nivel.setBackground(new Color(0,153,153));
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select username from usuarios where username = '" + username + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                tf_username.setBackground(Color.yellow);
                JOptionPane.showMessageDialog(null, "Usuario no disponible");
                cn.close();
            } else {

                cn.close();

                if (validacion == 0) {
                    try {
                        Connection cn1 = Conexion.conectar();
                        PreparedStatement pst1 = cn1.prepareStatement(
                                "insert into usuarios values (?,?,?,?,?,?,?,?)");
                        pst1.setInt(1, 0);
                        pst1.setString(2, nombre);
                        pst1.setString(3, telefono);
                        pst1.setString(4, username);
                        pst1.setString(5, pass);
                        pst1.setString(6, nivel);
                        pst1.setString(7, "Activo");
                        pst1.setString(8, user);

                        pst1.executeUpdate();
                        cn1.close();

                        Limpiar();

                        tf_username.setBackground(Color.green);
                        tf_pass.setBackground(Color.green);
                        tf_nombre.setBackground(Color.green);
                        tf_telefono.setBackground(Color.green);
                        box_nivel.setSelectedIndex(0);

                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                        this.dispose();
                    } catch (SQLException e) {
                        System.err.println("Error en registrar usuario" + e);
                        JOptionPane.showMessageDialog(null, "Error, contacte al administrador");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al validar usuario" + e);
            JOptionPane.showMessageDialog(null, "Eror, contacte al administrador");
        }
    }//GEN-LAST:event_boton_registrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ventanas_abiertas.remove(ventanas_abiertas.indexOf("registrar"));
    }//GEN-LAST:event_formWindowClosed

    private void footerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Por soporte tecnico comuniquese al e-mail: soporte@lachucha.com.ar");
    }//GEN-LAST:event_footerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_registrar;
    private javax.swing.JComboBox<String> box_nivel;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        tf_username.setText("");
        tf_pass.setText("");
        tf_nombre.setText("");
        tf_telefono.setText("");
        box_nivel.setSelectedIndex(0);
    }
}
